### ISSUE TITLE
Large fraction of time spent in global sorting of domain.c

### ISSUE THREAD

**Issue by rainwoodman** [rainwoodman/MP-Gadget#107]
A recent test on e7ffb52267 by @andersdot on a 128^3 simulation shows that the global sorting in domain.c took about 15% of time. This can be fully avoided if we use a local sorting. However, it will increase the time merging the toptree. 

In 3a6141e I added a flag DomainUseGlobalSorting, which can be set to 0 to disable the global sorting from parameter files:
```
DomainUseGlobalSorting = 0
```

@andersdot , is it easy for you to rerun the same test with this new flag (after updating the code). It may be able to reduce the wall-clock time by 15%.

**Comment by sbird** [comment]
Close this one too?
