### ISSUE TITLE
Softening cleanup

### ISSUE THREAD

**Issue by sbird** [rainwoodman/MP-Gadget#123]
We will have three parameters:
1 - Collisionless softening (which is comoving) and set as a fraction of mean particle separation.
2 - We will have a collisional softening, which is adaptive if zero, and otherwise a fraction of mean DM separation. Probably adaptive is the default.
3 - Parameter giving Ngrid (optional) for multi-grid simulations. If 0, compute from DM type 1 totnumpart, otherwise use it.

Everything is always comoving.

**Comment by andreufont** [comment]
Hi @sbird, 

Somewhat related to this. It would be great to have a bit of documentation / recommendations in the configuration files about what values to use. Right now in my sims I'm using the settings that you sent us at some point (see below), but I have no idea whether I should be scaling these with box size, mean particle separation, or whether these should be thought as universal. 

SofteningGas = 2.60417333333
SofteningGasMaxPhys = 2.60417333333
SofteningHalo = 2.60417333333
SofteningHaloMaxPhys = 2.60417333333
SofteningDisk = 2.60417333333
SofteningDiskMaxPhys = 2.60417333333
SofteningBulge = 2.60417333333
SofteningBulgeMaxPhys = 2.60417333333
SofteningStars = 2.60417333333
SofteningStarsMaxPhys = 2.60417333333
SofteningBndry = 2.60417333333
SofteningBndryMaxPhys = 2.60417333333

**Comment by sbird** [comment]
You want all those settings to be 1/30 of the mean interparticle spacing.

**Comment by andreufont** [comment]
Great. Should this be set as a default? As in: if you don't provide any value for these, they are automatically set to 1/30 times mean particle spacing.

**Comment by sbird** [comment]
Yes - they should also just be one parameter. if you feel like implementing the plan described in this issue that would be great :)

**Comment by rainwoodman** [comment]
I'll take care of this while setting up the NERSC CI.
