### ISSUE TITLE
"make clean" does not remove genic- objects 

### ISSUE THREAD

**Issue by andreufont** [rainwoodman/MP-Gadget#132]
In MP-Gadget, if I type "make clean" I would expect both MP-Gadget and MP-GenIC to get cleaned.

MP-GenIC itself and all MP-Gadget objects are deleted, but some objects (like genic-main.o) survive the cleaning. 

Is this a bug, or a feature?

**Comment by rainwoodman** [comment]
bug!

**Comment by sbird** [comment]
But it is because those modules are leftover from a previous build,  before I moved genic to a subfolder. Once you delete them once they will never re-appear.

**Comment by andreufont** [comment]
You are completely right Simeon. Sorry, you can close the ticket!

**Comment by sbird** [comment]
Ok!
