### ISSUE TITLE
Add inverted IC to GenIC

### ISSUE THREAD

**Issue by rainwoodman** [rainwoodman/MP-Gadget#145]
It's a four line change. Elena has showed me the diff set for doing this.
I'll try to get her to file a PR around the week.

**Comment by andreufont** [comment]
Is this similar to the paired simulations suggested by Pontzen et al. (2016)? If so, @andersdot (Lauren Anderson) is working on this and she already has code to add this to MP-GenIC. She could open a new branch and submit a PR.

**Comment by rainwoodman** [comment]
It is. If Lauren posts a PR, then we can ask Elena to review the patch.

**Comment by andersdot** [comment]
Oh sweet, will do !
