### ISSUE TITLE
Restart from snapshot and/or checkpoint

### ISSUE THREAD

**Issue by andersdot** [rainwoodman/MP-Gadget#157]
Does mp-gadget do checkpointing? I don't see any files that look like a checkpoint 

Is it possible to restart from a snapshot?

**Comment by rainwoodman** [comment]
If I remember accurately:

If you rerun with mode==1
MP-Gadget 1 
It will restart from the latest snapshot. Or you can manually specify 
MP-Gadget 2 003
to restart with snapshot 003.

**Comment by sbird** [comment]
It will also automatically write a snapshot when it reaches TimeLimitCPU

**Comment by andersdot** [comment]
You still need the paramfile in there, for example: MP_Gadget paramfile 2 008

When I set the mode to 1, it says _[ 000000.00 ] Task 3: Last Snapshot number is -1_. Is it looking for a specific file with the last snapshot number in it?

When I set the mode to 2 and give it a snapshot number, it gets the following error: 
_[ 000092.08 ] Reading snapshot /mnt/ceph/users/landerson/lyalphaFixedA/PART_008
[ 000094.47 ] Allocated 2944 MByte for particle storage.
[ 000094.47 ] Allocated 2560 MByte for storage of SPH data.
[ 000094.64 ] Task 3: Failed to read from block: Over the end of file @(bigfile.c:626)_

**Comment by sbird** [comment]
That error suggests one of the blocks is corrupted. I suspect this is because your last run crashed in the middle of a write? I would try restarting from snapshot 7 (and double-check you are not out of disc space).

If that does not work, try the below patch, which can tell us which block is corrupted:
+++ b/petaio.c
@@ -578,7 +578,7 @@ int petaio_read_block(BigFile * bf, char * blockname, BigArray * array, int requ
             endrun(1, "Failed to seek: %s\n", big_file_get_error_message());
     }
     if(0 != big_block_mpi_read(&bb, &ptr, array, All.IO.NumWriters, MPI_COMM_WORLD)) {
-        endrun(1, "Failed to read from block: %s\n", big_file_get_error_message());
+        endrun(1, "Failed to read from block %s: %s\n", big_file_get_error_message());
     }
     if(0 != big_block_mpi_close(&bb, MPI_COMM_WORLD)) {
         endrun(0, "Failed to close block at %s:%s\n", blockname,

**Comment by andersdot** [comment]
I restarted with a file that the simulation had for sure completely written. Below is the error which shows 0/Position is corrupted, and then below that I pasted the sizes of the various files in 0/Position. Do any of them look funny to you? 

[ 000010.11 ] Reading snapshot /mnt/ceph/users/landerson/lyalphaFixedA/PART_002
[ 000010.65 ] Allocated 420.571 MByte for particle storage.
[ 000010.65 ] Allocated 365.714 MByte for storage of SPH data.
[ 000010.70 ] Task 17: Failed to read from block: 0/Position
[ 000010.70 ] Task 27: Failed to read from block: 0/Position
[ 000010.70 ] Task 14: Failed to read from block: 0/Position
[ 000010.70 ] Task 15: Failed to read from block: 0/Position
[ 000010.70 ] Task 16: Failed to read from block: 0/Position
[ 000010.70 ] Task 18: Failed to read from block: 0/Position
[ 000010.70 ] Task 19: Failed to read from block: 0/Position
[ 000010.70 ] Task 20: Failed to read from block: 0/Position
[ 000010.70 ] Task 21: Failed to read from block: 0/Position
[ 000010.70 ] Task 22: Failed to read from block: 0/Position
[ 000010.70 ] Task 23: Failed to read from block: 0/Position
[ 000010.70 ] Task 24: Failed to read from block: 0/Position
[ 000010.70 ] Task 25: Failed to read from block: 0/Position
[ 000010.70 ] Task 26: Failed to read from block: 0/Position


-bash-4.2$ ls -lrt
total 392754
-rw-rw-r-- 1 landerson landerson        0 Oct 31 16:49 attr-v2
-rw-rw-r-- 1 landerson landerson 12567888 Oct 31 16:49 000011
-rw-rw-r-- 1 landerson landerson 12567888 Oct 31 16:49 00000B
-rw-rw-r-- 1 landerson landerson 12567912 Oct 31 16:49 000012
-rw-rw-r-- 1 landerson landerson 12567888 Oct 31 16:49 000016
-rw-rw-r-- 1 landerson landerson 12567912 Oct 31 16:49 00000D
-rw-rw-r-- 1 landerson landerson 12567888 Oct 31 16:49 00000E
-rw-rw-r-- 1 landerson landerson 12567912 Oct 31 16:49 00000A
-rw-rw-r-- 1 landerson landerson 12567888 Oct 31 16:49 000013
-rw-rw-r-- 1 landerson landerson 12567888 Oct 31 16:49 00000C
-rw-rw-r-- 1 landerson landerson 12567888 Oct 31 16:49 000009
-rw-rw-r-- 1 landerson landerson 12567888 Oct 31 16:49 000014
-rw-rw-r-- 1 landerson landerson 12567912 Oct 31 16:49 000017
-rw-rw-r-- 1 landerson landerson 12567912 Oct 31 16:49 00001D
-rw-rw-r-- 1 landerson landerson 12567912 Oct 31 16:49 000015
-rw-rw-r-- 1 landerson landerson 12567888 Oct 31 16:49 000000
-rw-rw-r-- 1 landerson landerson 12567888 Oct 31 16:49 00001E
-rw-rw-r-- 1 landerson landerson 12567888 Oct 31 16:49 000008
-rw-rw-r-- 1 landerson landerson 12567912 Oct 31 16:49 00001A
-rw-rw-r-- 1 landerson landerson 12567888 Oct 31 16:49 000006
-rw-rw-r-- 1 landerson landerson 12567888 Oct 31 16:49 000018
-rw-rw-r-- 1 landerson landerson 12567888 Oct 31 16:49 000003
-rw-rw-r-- 1 landerson landerson 12567888 Oct 31 16:49 000004
-rw-rw-r-- 1 landerson landerson 12567912 Oct 31 16:49 000005
-rw-rw-r-- 1 landerson landerson 12567888 Oct 31 16:49 000019
-rw-rw-r-- 1 landerson landerson 12567888 Oct 31 16:49 000001
-rw-rw-r-- 1 landerson landerson 12567888 Oct 31 16:49 00001B
-rw-rw-r-- 1 landerson landerson 12567912 Oct 31 16:49 00001F
-rw-rw-r-- 1 landerson landerson 12567912 Oct 31 16:49 000007
-rw-rw-r-- 1 landerson landerson 12567912 Oct 31 16:49 000002
-rw-rw-r-- 1 landerson landerson 12567888 Oct 31 16:49 00001C
-rw-rw-r-- 1 landerson landerson 12567888 Oct 31 16:49 000010
-rw-rw-r-- 1 landerson landerson 12567912 Oct 31 16:49 00000F
-rw-rw-r-- 1 landerson landerson     1177 Oct 31 16:49 header
-bash-4.2$

**Comment by sbird** [comment]
Hm, that is a puzzle. It looks fine by eye. Can you open the snapshot in python with "import bigfile   bf = bigfile.BigFile("output/PART_002")" or does that error too?

**Comment by andersdot** [comment]
that appears to be good
>>> import bigfile
>>> bf = bigfile.BigFile('PART_002')
>>> bf
<bigfile.BigFile object at 0x2aaabaef67e0>

**Comment by sbird** [comment]
What about the part array? Can you do np.max(bf["0/Position"][:]) without problems (and with a reasonable answer, ie, the box size)?

**Comment by andersdot** [comment]
It reads it in and gives a reasonable answer 
>>> np.max(bf["0/Position"][:])
>>> 19999.998666437968

My runs keep hanging when it gets to writing files, usually around z=4, a totally different issue but maybe linked?

**Comment by sbird** [comment]
It is possible. Certainly it should not hang when writing files. I don't suppose the copy of bigfile in the Gadget tree is out of date somehow is it? depends/bigfile should be revision 3df334755b 

You could also try manually doing "rm depends/lib/libbigfile*" and recompiling, just to make sure there isn't some old version hanging about somehow.

Otherwise I'm stuck...maybe Yu has some ideas?

**Comment by andersdot** [comment]
a 'git show' in depends/bigfile gives 

commit 5defc41c9ccd28cb9e3e01d4e885a1337e3d09cb
Author: Yu Feng <rainwoodman@gmail.com>
Date:   Wed Aug 9 18:16:04 2017 -0700

    bump version.

diff --git a/bigfile/version.py b/bigfile/version.py
index 57d2eb7..caaa49f 100644
--- a/bigfile/version.py
+++ b/bigfile/version.py
@@ -1,3 +1,3 @@
 
-__version__ = "0.1.34"
+__version__ = "0.1.35"

**Comment by sbird** [comment]
@rainwoodman : I am out of ideas. What do you think?

**Comment by andersdot** [comment]
The computing core here at CCA is looking into filesystem issues, both the hanging while writing files and corrupt looking files make it sound like something fishy is going on at the cluster level 

The computer core wants to understand the file access patterns of the code a bit, especially how files in directories like /mnt/ceph/users/landerson/lyalphaVaried3/PIG_004/FOFGroups/BlackholeAccretionRate are created.  Is each MPI rank writing a separate output file?

**Comment by rainwoodman** [comment]
No. Usually MPI ranks write to the same output BLOB file (files like 000000, xxx). We expect the filesystem to have POSIX 'atomic-write` semantic when operating over several nodes.  Usually Lustre supports full POSIX unless the config is messed up. GPFS from IBM works fine too. NFS needs some special configuration (disable write caching), but we never really tested bigfile on NFS very well. What file system are you running on?

The fact that the serial version was able to read successfully suggests it is a file system glitch. 
But to be sure, could you cat the content of header in the folder? The declared number of items shall be consistent with the length of each BLOB file (number of bytes per item times the number of items)

**Comment by rainwoodman** [comment]
You can point the core to here for additional information
https://github.com/rainwoodman/bigfile

**Comment by andersdot** [comment]
Thanks @rainwoodman, I wasn't sure what you meant by the declared number of items, here is the header file in 0/Positions  

DTYPE: <f8
NMEMB: 3
NFILE: 112
000000: 149442 : 439311972 : 30867
000001: 149442 : 444492450 : 34080
000002: 149442 : 443508027 : 32682
000003: 149442 : 447805060 : 4405
000004: 149442 : 452135277 : 9312
000005: 149442 : 444267309 : 5544
000006: 149442 : 448021326 : 24066
000007: 149442 : 450523782 : 36192
000008: 149442 : 451626283 : 24598
000009: 149442 : 455094006 : 18966
00000A: 149442 : 454279300 : 56215
00000B: 149442 : 451519416 : 48801
00000C: 149442 : 447295629 : 19254
00000D: 149442 : 444860618 : 9038
00000E: 149442 : 448218242 : 24377
00000F: 149442 : 445941948 : 41808
000010: 149442 : 448730243 : 12098
000011: 149442 : 449154292 : 42937
000012: 149442 : 453456638 : 19973
000013: 149442 : 451062433 : 50563
000014: 149442 : 455684725 : 19870
000015: 149442 : 457300021 : 62326
000016: 149442 : 457995856 : 37276
000017: 149442 : 457154677 : 48052
000018: 149442 : 451625022 : 23337
000019: 149442 : 452071571 : 11141
00001A: 149442 : 454697507 : 15677
00001B: 149442 : 451917258 : 53433
00001C: 149442 : 457361151 : 57921
00001D: 149442 : 453004877 : 26957
00001E: 149442 : 456142253 : 18653
00001F: 149442 : 458370828 : 19038
000020: 149442 : 460201598 : 14828
000021: 149442 : 459511201 : 45316
000022: 149442 : 459310352 : 41072
000023: 149442 : 460494778 : 45868
000024: 149442 : 459682306 : 19816
000025: 149442 : 461152427 : 48167
000026: 149442 : 460415090 : 31715
000027: 149442 : 458430299 : 12974
000028: 149442 : 453204736 : 30211
000029: 149442 : 457117930 : 11305
00002A: 149442 : 453668086 : 34816
00002B: 149442 : 453809219 : 44879
00002C: 149442 : 449376265 : 2770
00002D: 149442 : 451210884 : 2409
00002E: 149442 : 447890643 : 24453
00002F: 149442 : 448516915 : 60910
000030: 149442 : 447911815 : 45625
000031: 149442 : 451058681 : 46811
000032: 149442 : 455379086 : 41906
000033: 149442 : 457242724 : 5029
000034: 149442 : 457556592 : 56757
000035: 149442 : 453436340 : 65210
000036: 149442 : 453527372 : 25172
000037: 149442 : 453269722 : 29662
000038: 149442 : 453766663 : 2323
000039: 149442 : 457849174 : 21664
00003A: 149442 : 459720802 : 58312
00003B: 149442 : 459585985 : 54565
00003C: 149442 : 455585135 : 51350
00003D: 149442 : 455551080 : 17295
00003E: 149442 : 455198497 : 57922
00003F: 149442 : 456438729 : 52989
000040: 149442 : 459352138 : 17323
000041: 149442 : 459998945 : 8780
000042: 149442 : 460726094 : 15044
000043: 149442 : 456777042 : 63627
000044: 149442 : 456169314 : 45714
000045: 149442 : 456884679 : 40194
000046: 149442 : 457084109 : 43019
000047: 149442 : 461223811 : 54016
000048: 149442 : 461177751 : 7956
000049: 149442 : 462771203 : 28568
00004A: 149442 : 463163204 : 27359
00004B: 149442 : 463177769 : 41924
00004C: 149442 : 462734353 : 57253
00004D: 149442 : 462104983 : 17698
00004E: 149442 : 462144370 : 57085
00004F: 149442 : 461681388 : 52848
000050: 149442 : 461849749 : 24604
000051: 149442 : 462638438 : 26873
000052: 149442 : 463083275 : 12965
000053: 149442 : 462543649 : 63154
000054: 149442 : 461894938 : 4258
000055: 149442 : 460413145 : 29770
000056: 149442 : 460199108 : 12338
000057: 149442 : 460804852 : 28267
000058: 149442 : 460839045 : 62460
000059: 149442 : 460709510 : 63995
00005A: 149442 : 459755853 : 27828
00005B: 149442 : 459761994 : 33969
00005C: 149442 : 457715388 : 18948
00005D: 149442 : 453860700 : 30825
00005E: 149442 : 455450719 : 48004
00005F: 149442 : 454351878 : 63258
000060: 149442 : 455668456 : 3601
000061: 149442 : 456273115 : 18445
000062: 149442 : 453416002 : 44872
000063: 149442 : 453400803 : 29673
000064: 149442 : 451935913 : 6553
000065: 149442 : 456510555 : 59280
000066: 149442 : 457001483 : 25928
000067: 149442 : 457797435 : 35460
000068: 149442 : 457958720 : 140
000069: 149442 : 457513401 : 13566
00006A: 149442 : 453317993 : 12398
00006B: 149442 : 451118326 : 40921
00006C: 149442 : 452879043 : 32193
00006D: 149442 : 449627250 : 57150
00006E: 149442 : 446359800 : 915
00006F: 149443 : 448626004 : 38929

**Comment by sbird** [comment]
It looks like the file system is missing numerous blob files the header expects to be present.

**Comment by rainwoodman** [comment]
which could be triggered by a disk quota error or just a glitch.. what FS is it?

**Comment by andersdot** [comment]
blob files huh? hah is that the official term? :P The computing core here noticed some glitches with the filesystem while I was running my jobs and is submitting a patch, so hopefully I can rerun soon. I'll keep you guys posted with success or feedback from them, and what filesystem we run on (I'm not sure but asked)

**Comment by andersdot** [comment]
From the computing core:

"We use ceph as the filesystem.  At this point I'm convinced that this is a bug in ceph that causes the hangs, and not a bug in the code you are running.  In fact, I've been in contact with the ceph developers, and there is a candidate fix for the issue as of today.  Unfortunately the fix touches a pretty critical portion of ceph so I can't quite deploy it to our production system without some more testing/reviews (i affects the whole storage system, not just specific test nodes)."

**Comment by rainwoodman** [comment]
Yes BLOB file is the best name I could come up with for those hex named files.

I am a bit concerned about the second point of ceph's posix gotchas:

http://docs.ceph.com/docs/jewel/cephfs/posix/

Depending on the definition of ``object`` it may be an issue or not. We open a BLOB file and write to it sharedly. Though no two clients write to the same section of a file at the same time. Could you consult this with the computing core?

**Comment by andersdot** [comment]
I'll initiate an email between you guys with this suggestion.

**Comment by sbird** [comment]
Shall we close this one, since they seem to have a fix on the cluster?

**Comment by andersdot** [comment]
I think so, I'll reopen it if I see another problem after the fix on our side

**Comment by sbird** [comment]
Cheers.
