### ISSUE TITLE
Compiling on coma 

### ISSUE THREAD

**Issue by kuanweih** [rainwoodman/MP-Gadget#166]
There is an error when compiling MP-Gadget on coma and it says:

Compiling timestep.c
timestep.c(178): error: expected an operator
      #pragma omp parallel for reduction(min: mTimeBin) reduction(+: badstepsizecount)
                                         ^

compilation aborted for timestep.c (code 2)
make: *** [/home/kuanweih/MP-Gadget/timestep.o] Error 2

**Comment by rainwoodman** [comment]
@sbird  we need to make a decision on the version of openmp to use. Looks like compilers from centos6.x doesn't support min in reduction?

**Comment by rainwoodman** [comment]
@kuanweih a workaround is to use a newer compiler. What if you ask the admin if there is any compiler that supports openmp 3.1 (which supports reduction on min)

**Comment by sbird** [comment]
My apologies - I see RHEL 6 only supports 3.0 and reduction is 3.1 . We have also used atomic read/write in forcetree.c, which might be difficult. I am happy to avoid the reduction - it is easy enough.

**Comment by kuanweih** [comment]
@rainwoodman 
This is what I got from the admin:

-----
The latest Intel C/C++ compiler on coma should support openmp 3.1:

 From http://www.openmp.org/resources/openmp-compilers/
> Intel C/C++/Fortran   Windows, Linux, and MacOSX.
> OpenMP 3.1 C/C++/Fortran fully supported in version 12.0, 13.0, 14.0 compilers

Here's the newest version of the Intel C++ compiler on the cluster now:
> [root@coma rpm]# /opt/intel/composer_xe_2013_sp1.0.080/bin/iccvars.sh intel64
> [root@coma rpm]# /opt/intel/composer_xe_2013_sp1.0.080/bin/intel64/icc --version
> icc (ICC) 14.0.0 20130728
> Copyright (C) 1985-2013 Intel Corporation.  All rights reserved.
-----

I am confused now. It seems the compiler on coma supports openmp 3.1. So what might cause the problem?

**Comment by sbird** [comment]
That is a puzzle. Probably those compilers are not being used: perhaps you have the wrong modules loaded. What does mpicc --version say?

**Comment by sbird** [comment]
Shall we just say that we require openmp 3.1 and close this? It seems that there should be compilers which can handle it around.

**Comment by rainwoodman** [comment]
I'll add an assertion on OPENMP version, and die if not > 3.1

**Comment by rainwoodman** [comment]
Done by 9c797e77
