### ISSUE TITLE
FOF inconsistency with nbodykit.

### ISSUE THREAD

**Issue by rainwoodman** [rainwoodman/MP-Gadget#168]
It was reported that the output of FOF is inconsistent with that from nbodykit in all mass ranges. I will look into this.

**Comment by rainwoodman** [comment]
We understood was due to a difference in linking length. I am waiting for @zdplayground to report back on the consistenty of ll=0.28 catalog from nbodykit and MP-Gadget.

**Comment by zdplayground** [comment]
Yu, we met some problem broadcasting system libraries, i.e.,
when I ran
++ bcast /usr/common/contrib/bccp/python-mpi-bcast/nersc/cori/system-libraries.tar.gz /usr/common/contrib/bccp/anaconda3/envs/bccp-anaconda-3.6.tar.gz
++ srun -n 4 /global/common/cori/contrib/bccp/python-mpi-bcast/bcast -p /dev/shm/local /usr/common/contrib/bccp/python-mpi-bcast/nersc/cori/system-libraries.tar.gz /usr/common/contrib/bccp/anaconda3/envs/bccp-anaconda-3.6.tar.gz,

it complains that package file /usr/common/contrib/bccp/python-mpi-bcast/nersc/cori/system-libraries.tar.gz not found.
But I checked the file, it's there, so I'm confused how to solve it.

**Comment by rainwoodman** [comment]
If you rerun does it occur again? This can occur during the time of day
when the binaries are rebuilt.

**Comment by zdplayground** [comment]
Yes, it still occurs. Could you try it in your account?

**Comment by rainwoodman** [comment]
Try again? I meseed up the file permissions.

**Comment by zdplayground** [comment]
It works well now!

**Comment by sbird** [comment]
Shall we close the bug?

**Comment by zdplayground** [comment]
Yes, I think so.
