### ISSUE TITLE
Domain decomposition problem for neutrino sims with small box size

### ISSUE THREAD

**Issue by Chris-Pedersen** [rainwoodman/MP-Gadget#172]
Running the example neutrino sim with small box size (10Mpc) crashes near the end with:

[ 011520.58 ] Note: the domain decomposition is suboptimum because the ceiling for memory-imbalance is reached
...
[ 011520.60 ] Task 23: Not enough memory for recvdispls 8192 bytes

The default sim worked fine. The full output is [here](https://github.com/rainwoodman/MP-Gadget/files/1540233/test_out.txt) and the Options.mk is the same as [#171](https://github.com/rainwoodman/MP-Gadget/issues/171).

**Comment by rainwoodman** [comment]
Looks like a bug to me. too many list entries in the memory allocate table.. @sbird?

**Comment by sbird** [comment]
I'll look into it tomorrow.

**Comment by sbird** [comment]
@Chris-Pedersen : Does this branch: https://github.com/rainwoodman/MP-Gadget/pull/173 fix your problem?

**Comment by Chris-Pedersen** [comment]
Seems to be fixed, the sim that crashed finishes fine now.
