### ISSUE TITLE
Entropy change in drift instead of kick

### ISSUE THREAD

**Issue by sbird** [rainwoodman/MP-Gadget#177]
At the moment we change the entropy in apply_short_range_kick. I wonder if we should move it to drift_all_particles? Then the entropy variable will always be evaluated at the drift time instead of the kick time.

As far as the hydro is concerned, we always use the EntropyPred() function to regain Entropy at the drift time *anyway*. So by syncing Entropy to the drift time we would avoid the need to do that. DtEntropy is computed in hydra.c from Entropy at drift time. As we drift all particles, even inactive ones, this would also mean that we would be using shorter timesteps for the Entropy calculation, but I don't think that will make any difference.

Entropy is also used in BlackHole for the SmoothedEntropy of the BH particle. I think it would be more physical to use the drift-time Entropy here.

The Entropy is finally used in the cooling step. The code computes the Internal Energy using the Entropy at the *end* of the current timestep, ie, at Ti_kick + (1<<TimeBin), and uses that to compute the cooling rate (except this is at the start of the timestep, so equivalent to computing Entropy at Ti_drift + (1<<TimeBin)/2). (It does something else on the star-forming eq. of state, which doesn't really matter because it is following the subgrid model anyway.) We should change cooling so that it uses the same Entropy value as currently.

Yu, do you see any reason why we shouldn't have Entropy follow the drift time instead of the kick time? Or Am I missing something? This could be an optimisation for the hydro because we would not need all the function calls for predictions.

**Comment by rainwoodman** [comment]
Currently, entropy is modified in two places

- sfr, called in compute acceleration, which occurs at 'F' operator; which occurs at the point where drift and kick are not synced.

- short range kick, which occurs twice per loop, once before SyncPoint, once after SyncPoint.

The entropy modification in sfr is a discontinuous source term (respect to time); so there is no need to worry about it. The second one is a continuous integration; and that's we are talking about.

The DtEntropy term is computed during the F operator. Are you sure the F operator we are supposed to the entropy predicted at the drift time? I smell it perhaps should be the entropy predicted in the future. This is hinted by the logic in cooling as well. We may have had introduced a bug when introducing the EntPred function.

**Comment by sbird** [comment]
Hmm, let's check and see what Gadget-2 does.

**Comment by rainwoodman** [comment]
The source code gives me headache. The Gadget2 paper said nothing about the entropy integration timeline. I suspect the situation is that no one knows..

I found this paper which may be of some use:

https://cg.informatik.uni-freiburg.de/intern/seminar/particleFluids_Monaghan%20-%20SPH%20-%202005.pdf

the time line is described by eq 5.37 and 5.38 -- but I don't see any entropy here!

**Comment by sbird** [comment]
So now I look more closely the predicted entropy is only used for the Pressure-Entropy SPH.
Looking back at old versions of the code I see that the Pressure was computed using the Entropy at current (drift) time for Pressure-Entropy SPH and at the *end* of the timestep for "standard" SPH.

Things like:
#ifdef DENSITY_INDEPENDENT_SPH
        SPHP(i).Pressure = pow(SPHP(i).EntVarPred*SPHP(i).EgyWtDensity,GAMMA);
#else
        SPHP(i).Pressure = (SPHP(i).Entropy + SPHP(i).DtEntropy * dt_entr) * pow(SPHP(i).Density, GAMMA);
#endif

So we should check the Pressure-Entropy paper and if that fails, ask Phil Hopkins.

**Comment by sbird** [comment]
No, sorry, I misread: the pressure was always computed using entropy at the drift time, even for standard SPH. It was just obscured.

For the cooling see here: https://arxiv.org/abs/1706.00030 : the cooling should use internal energy at the end of the timestep for this implicit scheme. But it is a little weird that Gadget uses it for the density estimation, especially because cooling means the entropy will never actually *be* that value.

**Comment by rainwoodman** [comment]
You just said pressure was always computed using entropy at the drift time. So it appears in gadget only cooling uses the 'predicted' future entropy. What we called predicted entropy is just entropy at the drift time.

However, the time step is updated between two half kicks. I feel this may get into the way if we really align entropy to drifts.

**Comment by sbird** [comment]
You are right - I said something confused. What do you think would be the problem with updating the timestep between the kicks? Are you worried about the Courant condition calculation?

**Comment by rainwoodman** [comment]
I haven't been able to think this through. I worry that we don't know the correct size of the future time step for the prediction at the F operator (cooling) if the entropy is aligned with drift.

**Comment by sbird** [comment]
Ah, I see. Yes, that is a concern. Although - isn't it already a concern with the current code?

I think the best way to know for sure is to try to do it - probably initially with two entropy variables, asserting that they give the same answer everywhere they are used. You've convinced me that there is no obvious reason why this definitely can't work, so thanks for helping me think it through!

**Comment by rainwoodman** [comment]
Sure. One last point: I feel that the split around the two half kicks magically avoided the issue.

**Comment by sbird** [comment]
Yes, that makes sense. Because the first half of the kick happens with the old timestep, and the second half happens with the new timestep?

**Comment by rainwoodman** [comment]
Yes.

**Comment by sbird** [comment]
Having now implemented this, I found that our entropy prediction is actually completely broken...

This does make a bit of a difference, because hydro_force, which computes the adiabatic change in entropy, is computed before apply_half_kick() is done, so the kick time is not synchronized to the drift time. If Entropy is a kick variable, DtEntropy for the new timestep is used from t- dt/2 -> t+dt/2. If it is a drift variable, we have DtEntropy for the new timestep from t -> t+ dt.

However, because DtEntropy is used in EntropyPred(), the new DtEntropy depends on the DtEntropy of the neighbour particles, and so will give a different answer depending on whether a neighbouring particle has been evaluated yet. This is quite a bad bug, and I suspect some variant of it may be present in a large number of Gadget versions.

See https://github.com/rainwoodman/MP-Gadget/pull/186

**Comment by rainwoodman** [comment]
But without the EntropyPred function there is no bug -- EntPredVar variable used to be computed in density.c usually, which occurs before hydra.c starts to update it -- thus at least P-Gadget and PSPH-Gadget were fine.

**Comment by sbird** [comment]
You are right - that is good to know.

**Comment by rainwoodman** [comment]
Closed by #186
