### ISSUE TITLE
Compile error since refactor

### ISSUE THREAD

**Issue by Chris-Pedersen** [rainwoodman/MP-Gadget#205]
After cloning the repo and running the bootstrap since the refactor, I'm getting the error:
```
[chrisp@hypatia-login MP-Gadget]$ make
cd libgadget; make
make[1]: Entering directory `/home/chrisp/Codes/MP-Gadget/libgadget'
mkdir -p `dirname config.h`
MPICC="mpicc" CFLAGS="-fopenmp -O3 -g -Wall -ffast-math -march=native -DOPENMP_USE_SPINLOCK -DSFR -DSTACKTRACE -I/share/apps/gsl-2.4/include/ -I../depends/include -I../ "-DLOW_PRECISION=double" "-DHIGH_PRECISION=double"" OPT="-DOPENMP_USE_SPINLOCK -DSFR -DSTACKTRACE" OPTIMIZE="-fopenmp -O3 -g -Wall -ffast-math -march=native" VERSION="5.0.0.dev1" bash makeconfig.sh config.h
Compiling gdbtools.c
Compiling hci.c
Compiling fof.c
fof.c:11:20: fatal error: mpsort.h: No such file or directory
compilation terminated.
make[1]: *** [.objs/fof.o] Error 1
make[1]: Leaving directory `/home/chrisp/Codes/MP-Gadget/libgadget'
make: *** [all] Error 2
```

**Comment by rainwoodman** [comment]
The .. in -I looked suspicious.  I think it dhsll be sn absolute path. I
will be able to look further tomorrow.  Travis compiked fine so i suspect
it must be a compiler compare issue. Which are you using?

**Comment by sbird** [comment]
Did you check whether mpsort.h actually exists in ../depends/include?

**Comment by Chris-Pedersen** [comment]
Ah the files in depends/ weren't compiled. If you go into depends and `make` manually everything compiles, but only if you edit line 1 of https://github.com/rainwoodman/MP-Gadget/blob/master/depends/Makefile from `CONFIG = ../../Options.mk` to `CONFIG = ../Options.mk`. It looks like that was one of the first things the old Makefile did, but the new one doesn't?
