### ISSUE TITLE
example/lya run crashes due to metallicity files

### ISSUE THREAD

**Issue by andreufont** [rainwoodman/MP-Gadget#80]
I can now run the example in examples/dm-only, but when I try examples/lya I get the following error:

[ 000000.00 ] Radiation is enabled in Hubble(a). Following CAMB convention: Omega_Tot - 1 = 8.60162e-05
[ 000000.00 ]
[ 000000.01 ] Read ionization table for z=0 - 13.9624, with 236 rows in file `../TREECOOL_fg_june11'.
[ 000000.01 ] Cannot open ../cooling_metal_UVB.hdf5 MetallicityInSolar_bins

**Comment by sbird** [comment]
Fixed now

**Comment by andreufont** [comment]
Great. Thanks!
