### ISSUE TITLE
Not all particles are processed in lya runs (with MPI)

### ISSUE THREAD

**Issue by andreufont** [rainwoodman/MP-Gadget#81]
When I run the example under examples/lya, I get a crash half way through the evolution (at z=3.89264), with the message copied below. Apparently the code doesn't pass one of the tests in gravpm.c, since not all particles have been processed. 

The crash is not stochastic, different runs get the same amount of particles processed in each task. 

However, only crashes when running with MPI. 

Error message below:

[ 000060.65 ] Task 2: Processed only 56454 particles out of 56509
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 2 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[ 000060.65 ] Task 4: Processed only 65936 particles out of 66025
[ 000060.65 ] Task 7: Processed only 62622 particles out of 62670
[ 000060.66 ] Task 0: Processed only 68937 particles out of 69036
[ 000060.65 ] Task 3: Processed only 63071 particles out of 63125
[ 000060.65 ] Task 5: Processed only 66397 particles out of 66493
[ 000060.65 ] Task 1: Processed only 72962 particles out of 73062
[ 000060.65 ] Task 6: Processed only 67290 particles out of 67368

**Comment by sbird** [comment]
Try cherry-picking 3c9b457 from the bluetides-ii branch, and see if that helps.

**Comment by andreufont** [comment]
Thanks, Simeon, I'll try it now. 

By the way, the code compile well in Hypatia, and I had exactly the same crash there.

**Comment by rainwoodman** [comment]
@andreufont 
If the one Simeon mentioned doesn't fix the issue, apply this one surely should
0b13c3520cde4391cc23d9188d20ec2708f506b6

Could you send the parameter file you used to produce this crash? It looked like a small simulation?

**Comment by andreufont** [comment]
Hi Yu, 
I used the default files in examples/lya, from the master branch. 
I'll be on vacations 9 days, but in August I'll look again at it. Thanks!

**Comment by rainwoodman** [comment]
Thanks!

**Comment by rainwoodman** [comment]
I can confirm the first fix doesn't work.

**Comment by rainwoodman** [comment]
This happens because the BITFLAG_DEPENDS_ON_LOCALMASS flag is not properly maintained in our current timeline. 
When we drift particles, and rebuild the tree, some particles may have moved to TopLeaves that are hosted on other processes. Thus one always need to do a domain_exchange before rebuilding the tree. The master branch doesn't have domain_exchange, so we'll simply redo the decomposition.

**Comment by rainwoodman** [comment]
This wouldn't have affected the statictree branch, btw.

**Comment by sbird** [comment]
Another great reason to be doing statictree :)

**Comment by andreufont** [comment]
Hi! I'm back on it. I just wanted to let you know that I was able to run a Lya simulation with MPI both on my desktop and on Hypatia (our local cluster), so I guess this issue was solved over the summer. Thanks!

**Comment by rainwoodman** [comment]
Thanks for the update!
