### ISSUE TITLE
Replacing BitFlags with C bitfields

### ISSUE THREAD

**Issue by rainwoodman** [rainwoodman/MP-Gadget#83]
While working on #81 I realized it is not so easy to debug a code with those bitflags.
The masks are defined as macros and GDB  can't see them. Also hard to count the number of digits (and prone to mistakes) in binary.

A cleaner approach is to use C bitfields.

**Comment by sbird** [comment]
Fixed in forcetree-test branch: issue can be closed when that is merged.
