### ISSUE TITLE
Make Nmesh and Nsample 'optional' in GenIC.

### ISSUE THREAD

**Issue by rainwoodman** [rainwoodman/MP-Gadget#94]
These values are confusing and usually we just set Nmesh = Nsample = Ngrid anyways. See https://github.com/rainwoodman/MP-Gadget/issues/92#issuecomment-328055889

**Comment by sbird** [comment]
Agreed! I actually removed them entirely from S-GenIC.

**Comment by sbird** [comment]
Nsample is actually already ignored.
