### ISSUE TITLE
Time wraps around LYA test on higher resolution.

### ISSUE THREAD

**Issue by rainwoodman** [rainwoodman/MP-Gadget#95]
It is observed that the time stepping wraps around from z=1.58 back to z=2.0 with a negative dloga in some simulation set ups based on LYA. @sbird  any hints what might be wrong?

Forwarded from #92 .

**Comment by rainwoodman** [comment]
@andreufont Could you attach the full parameter files + log file? This will help me to identify a smaller test case that reproduces the wrapping around error you've seen.

**Comment by andreufont** [comment]
@rainwoodman, I tried adding the config files, but github wouldn't let me... I'll just copy paste below, but they are the default files except for the following changes:
In GenIC: 
Nmesh = 128 
Ngrid = 128 
Nsample = 128
BoxSize = 10000

In Gadget:
Nmesh = 256

It is an all MPI run.


localhost:~ font$ cat paramfile.genic 
OutputDir = output # Directory for output
FileBase = IC              # Base-filename of output files
Nmesh = 128 # This is the size of the FFT grid used to 
                            # compute the displacement field. One
                            # should have Nmesh >= Nsample.
Ngrid = 128 # number of particles per grid direction.
Nsample = 128 # k space sampling upper limit
BoxSize = 10000   # Periodic box size of simulation
Omega0 = 0.2814      # Total matter density  (at z=0)
OmegaLambda = 0.7186      # Cosmological constant (at z=0)
OmegaBaryon = 0.0464     # Baryon density        (at z=0)
ProduceGas = 1         # 1 = Produce gas  0 = no gas, just DM.
OmegaDM_2ndSpecies 0 = # Omega for a second dark matter species (at z=0)
HubbleParam = 0.697      # Hubble paramater (may be used for power spec parameterization)
Redshift = 9        # Starting redshift
Sigma8 = 0.810      # power spectrum normalization
SphereMode = 1         # if "1" only modes with |k| < k_Nyquist are
                           # used (i.e. a sphere in k-space), otherwise modes with
                           # |k_x|,|k_y|,|k_z| < k_Nyquist are used
                           # (i.e. a cube in k-space)
WhichSpectrum = 2         # "1" selects Eisenstein & Hu spectrum,
		                   # "2" selects a tabulated power spectrum in
                           # the file 'FileWithInputSpectrum'
                           # otherwise, Efstathiou parametrization is used
FileWithInputSpectrum = ../powerspectrum-wmap9.txt  # filename of tabulated input
                                                                   # spectrum (if used)
InputSpectrum_UnitLength_in_cm  = 3.085678e24 # defines length unit of tabulated
                                                                   # input spectrum in cm/h. 
                                                # Note: This can be chosen different from UnitLength_in_cm
ShapeGamma = 0.201     # only needed for Efstathiou power spectrum 
PrimordialIndex  0.971 = # may be used to tilt the primordial index
Seed = 181170    #  seed for IC-generator
UnitLength_in_cm = 3.085678e21   # defines length unit of output (in cm/h) 
UnitMass_in_g = 1.989e43      # defines mass unit of output (in g/cm)
UnitVelocity_in_cm_per_s = 1e5 # defines velocity unit of output (in cm/sec)
WDM_On = 0      # Putting a '1' here will enable a WDM small-scale
                            # smoothing of the power spectrum
WDM_Vtherm_On = 0      # If set to '1', the (warm) dark matter particles will
                            # receive an additional random thermal velocity
                            # corresponding to their particle mass
WDM_PartMass_in_kev = 10.0 # This is the particle mass in keV of the WDM particle

localhost:~ font$ cat paramfile.gadget 
#  Relevant files
InitCondFile = output/IC
OutputDir = output
TreeCoolFile = ../TREECOOL_fg_june11
MetalCoolFile = ../cooling_metal_UVB
OutputList = 0.1,0.2,0.2222222,0.25,0.2857,0.33333
SnapshotFileBase = snapshot
Nmesh = 256
# CPU time -limit
TimeLimitCPU = 43000 #= 8 hours
# Code options
TypeOfTimestepCriterion = 0
#  Characteristics of run
TimeMax = 0.33333
Omega0 = 0.2814      # Total matter density  (at z=0)
OmegaLambda = 0.7186      # Cosmological constant (at z=0)
OmegaBaryon = 0.0464     # Baryon density        (at z=0)
HubbleParam = 0.697      # Hubble paramater (may be used for power spec parameterization)
CoolingOn = 1
StarformationOn = 1
RadiationOn = 1
HydroOn = 1
StarformationCriterion = density
# Output frequency
CpuTimeBetRestartFile = 9000.0
# Accuracy of time integration
ErrTolIntAccuracy = 0.02 
MaxRMSDisplacementFac = 0.2
CourantFac = 0.15     
MaxSizeTimestep = 0.1
MinSizeTimestep = 0.05
# Tree algorithm, force accuracy, domain update frequency
ErrTolForceAcc = 0.005
#  Further parameters of SPH
DensityKernelType = quintic
DensityContrastLimit = 100   # max contrast for hydro force calculation
DensityResolutionEta = 1.0  # for Cubic spline 1.0 = 33
MaxNumNgbDeviation = 2
ArtBulkViscConst = 0.75
InitGasTemp = 580.0        # always ignored if set to 0 
MinGasTemp = 5.0    
# Memory allocation
PartAllocFactor = 2.0
BufferSize = 100          # in MByte
TopNodeAllocFactor = 0.20
# Softening lengths
MinGasHsmlFractional = 0.01
MaxGasVel = 3e5
SofteningGas = 50
SofteningHalo = 50
SofteningDisk = 0
SofteningBulge = 0           
SofteningStars = 50
SofteningBndry = 50             #This is BH
SofteningGasMaxPhys = 50
SofteningHaloMaxPhys = 50
SofteningDiskMaxPhys = 0
SofteningBulgeMaxPhys = 0           
SofteningStarsMaxPhys = 50
SofteningBndryMaxPhys = 50      #This is BH
#----------------------SFR Stuff-------------------------
CritPhysDensity = 0       #  critical physical density for star formation in
#  hydrogen number density in cm^(-3)
CritOverDensity = 57.7   #  overdensity threshold value
QuickLymanAlphaProbability = 1 # Set to 1.0 to turn dense gas directly into stars.
MaxSfrTimescale = 1.5     # in internal time units
TempSupernova = 1.0e8   #  in Kelvin
TempClouds = 1000.0   #  in Kelvin
FactorSN = 0.1
FactorEVP = 1000.0
WindModel = nowind
SnapshotWithFOF = 0
BlackHoleOn = 0
#----------------------BH Stuff-------------------------
BlackHoleFeedbackFactor = 0.05
BlackHoleFeedbackRadius = 0.
BlackHoleFeedbackRadiusMaxPhys = 0.
BlackHoleFeedbackMethod = spline | mass
SeedBlackHoleMass = 5.0e-5

**Comment by sbird** [comment]
Is this with the new timestepping (statictree head)? I will take a look on Monday.

**Comment by andreufont** [comment]
Yes, this is the statictree branch. Yu Feng  mentioned that I might not have used the latest version (by a few hours max), so I'll try again on Monday.

**Comment by sbird** [comment]
Commit  850f62dbb16 should fix this, so try it with current statictree head. At the very least you should not get the infinite loop: we check for reversed time explicitly and error if we find it.

**Comment by andreufont** [comment]
git pulled, running new tests now. I'll let you know when it finishes or crashes :-)

**Comment by andreufont** [comment]
Yes, the same run (configuration above) finished on both computers after updating the branches. 

However, in both computers I got an extra snapshot that was not in the requested output list:
- On my desktop the extra snapshot was at a=0.195185, and right after it printed the requested one at a=0.2.
- On Hypatia the extra snapshot was at a=0.281559, and right after it printed the requested one at a=0.2857. 

No idea why that would happen...

**Comment by sbird** [comment]
It is because you have CpuTimeBetRestartFile set. It outputs a snapshot automatically after a certain number of seconds of walltime has passed. Perhaps we should change the behaviour so that CpuTimeBetRestartFile is since the last "regular" snapshot? Perhaps we should also make it possible to disable the regular snapshotting and/or make the parameter optional? Yu, what do you think?

**Comment by andreufont** [comment]
I see! I wasn't aware of that. Thanks!

**Comment by rainwoodman** [comment]
@sbird Yes. Snapshot is a subset of checkpoint, so we shall do it that way.

**Comment by sbird** [comment]
See 0c862e4179
